### ISSUE TITLE
[0.1.1] Server Crash

### ISSUE THREAD

**Issue by ghost** [SuperCoder7979/cavebiomes#1]
## Description
Was playing on my server with two of my friends, and then there server crashed. Whenever we tried to log back in, the server crashed again. So, I had to remove the mod. Before the crash, my friend was mining in a cave. This is the first time I've experienced a crash on the server, and I had no previous issues with the past version of the mod.

## Crash Report
[crash-2020-04-02_23.41.00-server.txt](https://github.com/SuperCoder7979/cavebiomes/files/4424377/crash-2020-04-02_23.41.00-server.txt)

**Comment by jaskarth** [comment]
Oh, you need to update to 1.16. I'll make a 1.15 version in a sec

**Comment by ghost** [comment]
Okay cool. Just so you know, the 1.16 version was labeled 1.15.2 compatible.
