### ISSUE TITLE
Incompatable with yung's better caves

### ISSUE THREAD

**Issue by Fusion-Flux** [SuperCoder7979/cavebiomes#5]
When used with yung's better caves, cave biomes refuse to generate

**Comment by jaskarth** [comment]
Should be fixed in 0.5.0 :)

**Comment by Cluelesshobo** [comment]
Server Crashes dispite LocalWaterLevels is off.
Edit: Whoops should have posted logs.
https://hastebin.com/asusoserer.yaml
https://hastebin.com/idawetimoy.yaml

**Comment by jaskarth** [comment]
Can you please upload a crash log?
