### ISSUE TITLE
Unstable/crashes periodically during chunk generation

### ISSUE THREAD

**Issue by UnLuCkYcHaRrnS** [SuperCoder7979/cavebiomes#9]
Not sure what exactly the issue is, something about chunk generation with your caves for my machine causes the mod to be unstable. Lowering my render distance helps, but if I load too many chunks too fast it will crash my game

Minecraft log [https://paste.ee/p/GCD0a](url)
My dxdiag [DxDiag.txt](https://github.com/SuperCoder7979/cavebiomes/files/5426587/DxDiag.txt)

**Comment by jaskarth** [comment]
Hmm, try updating to 0.5.0 and see if the issue persists 😅
